# NumPy 2.0

> [官方API](https://docs.scipy.org/doc/numpy/reference/index.html)

NumPy库的标准导入方法(使用别名)：

In [160]:
import numpy as np

NumPy提供了一种比Python内置的list对象更加强大的数组对象——ndarray，即n维数组。NumPy中几乎所有的操作均基于ndarray。

注意，本文自此以后将__ndarray数组__简称为__数组__；提到__数组__，即指__ndarray对象__。

## 零. IPython常用的魔术命令

In [161]:
# 显示所有魔术命令
%magic

* `%run 文件名`：执行py程序的命令，例如`%run demo.py`，会在一个空的命名空间执行demo.py文件中的所有代码；
* `%time 语句`：输入代码的执行时间；
* `%timeit 语句`：多次执行代码，默认执行7大次，每大次里循环100000次该语句并计算平均时间，再将7大次的平均时间与标准差输出；
* `%timeit -n N -r R 语句`：定制化。

In [162]:
%time 1/(np.arange(10)+1)

CPU times: user 115 µs, sys: 225 µs, total: 340 µs
Wall time: 343 µs


array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [163]:
%timeit 1/(np.arange(10)+1)

4.52 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [164]:
%timeit -n 10 -r 1 1/(np.arange(10)+1)

54.5 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)


In [165]:
%timeit -n 10 -r 2 1/(np.arange(10)+1)

19.3 µs ± 8.02 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)


In [166]:
# 加个问号，获取帮助信息
%timeit?

## 一. 数组创建

数组的创建可以划分为两种路径：①从有到有；②从无到有；在__从无到有__中，需要重点掌握`np.random`模块，即使用一系列__随机数函数__从无到有地创建数组。

### 1. 从零创建

第一个参数，一般都是以Tuple表示的数组形状。

In [167]:
# 全零数组
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [168]:
# 全1数组
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [169]:
# 全指定值数组
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [170]:
# 单位矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [171]:
# 未初始化的数组: 创建一个元素未初始化的数组，注意未初始化并不代表元素是0
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [172]:
# 创建一个线性序列数组，一般常跟reshape配合生成多维数组
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
# 接受起始点、结束点、节点数量三个参数，均匀分配
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

### 2. 从有到有

使用`np.array()`从python的list(或tuple)创建数组。

In [174]:
np.array([1,2,3])

array([1, 2, 3])

In [175]:
np.array((1,2,3))

array([1, 2, 3])

In [176]:
# 使用dtype参数指定数组元素的类型
np.array([1,2,3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [177]:
# dtype可以是字符串，也可以是np的对象
np.array([1,2,3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [178]:
# 嵌套
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
# 复杂一点的例子，配合了列表解析
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [180]:
x = np.array([range(i,i+3) for i in [2,4,6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [181]:
# np.ones_like(a)
# 根据数组a的形状形成一个全1数组
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [182]:
# np.zeros_like(a)
# 根据数组a的形状形成一个全1数组
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [183]:
# np.full_like(a, val)
# 根据数组a的形状形成一个全val数组
np.full_like(x,111)

array([[111, 111, 111],
       [111, 111, 111],
       [111, 111, 111]])

### 3. 随机数函数 (From: 从有到有)

从__从无到有__中单独提出来，因为非常重要。

#### 1) 简单随机数函数

In [184]:
# 设定随机数种子
np.random.seed(0)

In [185]:
# np.random.random((d0,d1,...,dn))
# 返回一个或一组服从“0~1均匀分布”（包括0但不包括1）的随机样本值
np.random.random((2,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [186]:
# np.random.rand(d0,d1,...,dn)
# 作用于np.random.random相同
# If you want an interface that takes a shape-tuple as the first argument
# refer to np.random.random
np.random.rand(2,3)

array([[0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

In [187]:
# np.random.randn(d0,d1,...dn)
# 根据形状创建随机数数组，浮点数，标准正态分布
np.random.randn(2,3)

array([[ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826]])

In [188]:
# np.random.randint(low[,high,shape])
# 根据shape创建整数或整数数组，范围是[low,high)
# “If high is None (the default), then results are from [0,low)”
np.random.randint(0,100,(2,3))

array([[14, 39, 32],
       [65,  9, 57]])

#### 2) 高级随机数函数

In [189]:
# np.random.uniform(low, high, size)
# 产生具有均匀分布的数据
# low起始值，high结束值，size形状，[low,high)
np.random.uniform(0,100,(3,4))

array([[94.4668917 , 52.18483218, 41.466194  , 26.45556121],
       [77.42336894, 45.61503322, 56.84339489,  1.87898004],
       [61.76354971, 61.20957227, 61.69339969, 94.37480785]])

In [190]:
# np.random.normal(loc, scale, size)
# 产生具有正态分布的数据，loc均值，scale标准差，size形状
np.random.normal(5,2,(2,3))

array([[2.84344399, 7.79094454, 8.57496809],
       [3.86096547, 5.35077307, 4.07498892]])

In [191]:
# np.random.poisson(lam, size)
# 产生具有泊松分布的数据，lam随机事件发生率，size形状
np.random.poisson(2,(2,3))

array([[2, 1, 3],
       [1, 2, 1]])

#### 3) 随机重排

In [192]:
# np.random.shuffle(a)
# 根据数组a的第0轴进行随机排列，改变数组a
a = np.arange(10)
np.random.shuffle(a)
a

array([2, 4, 7, 3, 6, 8, 1, 0, 9, 5])

In [193]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
np.random.shuffle(b)
b

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [195]:
# np.random.permutation(a)
# 同上，但不改变数组a
c = np.arange(10)
np.random.permutation(c)

array([3, 6, 5, 8, 9, 7, 4, 2, 1, 0])

In [196]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
# np.random.choice(a, [,size, replace, p])
# 从1维数组a中以概率p抽取元素，形成size形状的新数组
# replace表示是否可以重用元素，默认为Ture
d = np.random.randint(100,201,(8,))
d

array([177, 121, 173, 100, 110, 143, 158, 123])

In [198]:
np.random.choice(d, (2,3))

array([[100, 173, 121],
       [173, 158, 100]])

In [199]:
np.random.choice(d, (2,3), replace=False)

array([[143, 121, 177],
       [110, 173, 123]])

In [200]:
np.random.choice(d, (2,3), p=d/np.sum(d))

array([[100, 123, 123],
       [177, 173, 177]])

## 二. 数据类型

数组包含__同一类型__的值，即元素类型必须相同。

构建数组时，使用关键字参数`dtype`来指定数据类型。可以使用字符串来指定，如`dtype='int16'`，也可以用对象来指定`dtype=np.int16`。

常用：
* `bool_`：布尔值
* `int32`：整型，范围从-2^31到-2^31-1
* `float32`：单精度浮点数
* `float64`：双精度浮点数

## 三. 数组属性

In [201]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
# 数组的维度，int
arr.ndim

2

In [203]:
# 数组的形状(每个维度的大小，从第0轴开始)
# 一般是一个tuple
arr.shape

(2, 3)

In [204]:
# 数组的总大小，shape中元素相乘
arr.size

6

In [205]:
# 数组元素的类型
arr.dtype

dtype('int64')

In [206]:
# 每个数组元素的字节大小
arr.itemsize

8

## 四. 索引

支持__正向索引__与__反向索引__。

In [207]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
a[1]

1

In [209]:
a[-2]

8

多维数组可以用一个中括号辅以逗号来获取__深层元素__，如`a[0,0]`和普通list的`a[0][0]`等价。

In [210]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
# 第2行第2列元素
b[1,1]

5

可以使用索引直接__修改数组__。注意，试图将一个浮点数插入到一个整型数组中，会发生无任何警告的__截断操作__（不是四舍五入）。

In [212]:
b[-1,-1]

11

In [213]:
b[-1,-1] = 199.9999999
b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 199]])

## 五. 切片

索引获取__单个值__，切片获取__子数组__。

语法为`x[start:stop:step]`，默认值分别为start=0, stop=size of dimension, step=1。step为负的时候表示__逆向截取__。

In [214]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
a[1:7]

array([1, 2, 3, 4, 5, 6])

In [216]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

多维数组的切片，不同维度用逗号分隔，进行操作。例如对于二维数组`x`，`x[:2, :3]`表示切到前两行+前三列。

In [217]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [218]:
b[:2,:2]

array([[0, 1],
       [4, 5]])

获取数组的__单行__或__单列__：将__切片__和__索引__配合使用。

In [219]:
# 单行
b[1,:]

array([4, 5, 6, 7])

In [220]:
# 单列
b[:,1]

array([1, 5, 9])

最后，关于__副本(copy)__和__视图(view)__：切片切出来的是view而非copy，因此对切片的修改会影响到原数组。

In [221]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
temp = b[0,:]
temp

array([0, 1, 2, 3])

In [223]:
temp[1] = 100
temp

array([  0, 100,   2,   3])

In [224]:
b

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

这样做可以__节省缓存空间__。可以使用`切片.copy()`获得副本；对副本操作，不会影响原数组。

## 六. 变形

`.reshape()`，常用于将一维数组扩展为多维数组：

In [225]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

将一个一维数组，转变成为二维的行或列的矩阵：

In [226]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [227]:
# 行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [228]:
# 列向量
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

`.resize()`，效果和reshape一样，但修改原数组——reshape是返回一个新的数组而原数组不变。

In [229]:
a = np.arange(10)
a.resize(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [230]:
a = np.arange(10)
a.reshape(2,5)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`.flatten()`，对数组进行降维，返回折叠后的一维数组，原数组不变。

In [231]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`.astype()`，对数组元素进行类型变换，注意astype方法一定会创建新的数组，即使两个类型一样。

In [233]:
# new_a = a.astype(new_type)
a = np.ones((2,2), dtype="int32")
a

array([[1, 1],
       [1, 1]], dtype=int32)

In [234]:
a.astype("float32")

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [235]:
a

array([[1, 1],
       [1, 1]], dtype=int32)

## 七. 拼接

将多个数组拼接成一个。

`np.concatencate()`，默认按照第0轴拼接，可以一次性拼接多个，但要把拼接的数组先以列表或元组的形式圈起来，如`np.concatencate([x,y,z])`。

In [236]:
a1 = np.arange(6).reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [237]:
addarr = np.array([6,7,8])
addarr

array([6, 7, 8])

In [238]:
add1 = addarr[np.newaxis, :]
np.concatenate([a1, add1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

对于多维数组的拼接，`np.concatencate([x,y], axix=指定轴)`。

In [239]:
add2 = addarr[:-1, np.newaxis]
np.concatenate([a1, add2], axis=1)

array([[0, 1, 2, 6],
       [3, 4, 5, 7]])

In [240]:
a1

array([[0, 1, 2],
       [3, 4, 5]])

`np.vstack`: 垂直栈。垂直方向对接，同样要把拼接的数组先以列表或元组的形式圈起来，但拼上去的一维数组不需要先转成2维再拼接，可以直接拼接。

In [241]:
np.vstack([a1,a1])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [242]:
np.vstack([a1,a1[0]])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [243]:
np.vstack([a1,a1[0][np.newaxis,:]])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

`np.hstack`：水平栈。水平方向拼接，同样要把拼接的数组先以列表或元组的形式圈起来。

In [244]:
np.hstack([a1,a1])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [245]:
np.hstack([a1,a1[:,1][:,np.newaxis]])

array([[0, 1, 2, 1],
       [3, 4, 5, 4]])

## 八. 分裂

`np.split(x, [...])`：第一个参数是要进行分裂的数组，第二个参数是一个索引列表，记录分裂点。

In [246]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


`np.vsplit()`: 垂直栈，分开。

In [247]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [248]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


`np.hsplit()`：水平栈，分开。

In [249]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 九. 通用函数

NumPy为什么快？向量化操作(vectorized)为数组计算提速。NumPy通过__通用函数(ufunc)__实现向量化操作。

### 1. 算术运算

原生的算术运算符，实质上是NumPy通用函数的封装器，例如`+`就是`np.add`的封装器。

In [250]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [251]:
x+2

array([2., 2., 2., 2., 2.])

In [252]:
np.add(x,2)

array([2., 2., 2., 2., 2.])

<table>
    <tr>
        <td>运算符</td>
        <td>对应的通用函数</td>
        <td>描述</td>
    </tr>
    <tr>
        <td>+</td>
        <td>np.add</td>
        <td>加法</td>
    </tr>
    <tr>
        <td>-</td>
        <td>np.subtract</td>
        <td>减法</td>
    </tr>
    <tr>
        <td>*</td>
        <td>np.multiply</td>
        <td>乘法</td>
    </tr>
    <tr>
        <td>/</td>
        <td>np.divide</td>
        <td>除法</td>
    </tr>
    <tr>
        <td>//</td>
        <td>np.floor_divide</td>
        <td>向下整除</td>
    </tr>
    <tr>
        <td>**</td>
        <td>np.power</td>
        <td>指数</td>
    </tr>
    <tr>
        <td>%</td>
        <td>np.mod</td>
        <td>取余</td>
    </tr>
</table>

### 2. 绝对值

In [253]:
np.random.seed(0)
x = np.random.randn(3,4)
x

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [254]:
np.abs(x)

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.97727788, 0.95008842, 0.15135721],
       [0.10321885, 0.4105985 , 0.14404357, 1.45427351]])

In [255]:
np.absolute(x)

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.97727788, 0.95008842, 0.15135721],
       [0.10321885, 0.4105985 , 0.14404357, 1.45427351]])

### 3. 三角函数

`np.sin`, `np.cos`, `np.tan`等。

### 4. 指数

`np.exp`(底数是e), `np.exp2`(底数是2)。

In [256]:
x = np.array([0,1,2,3])
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [257]:
np.exp2(x)

array([1., 2., 4., 8.])

### 5. 对数

`np.log`(底数是e)，`np.log2`(底数是2)，`np.log10`(底数是10)。

In [258]:
y = np.exp2([0,1,2,3])
y

array([1., 2., 4., 8.])

In [259]:
np.log(y)

array([0.        , 0.69314718, 1.38629436, 2.07944154])

In [260]:
np.log2(y)

array([0., 1., 2., 3.])

In [261]:
np.log10(y)

array([0.        , 0.30103   , 0.60205999, 0.90308999])

### 6. 其他函数

* `np.sqrt(x)`：平方根
* `np.rint(x)`：各元素四舍五入
* `np.modf(x)`：将数组中各元素的小数和整数部分以两个独立的数组形式返回
* `np.sign(x)`：计算数组各元素的符号值，1(+)，0，-1(-)

### 7. out参数

进行大量运算时，可以使用通用函数的`out`参数，直接指定一个用于存放运算结果的数组，这样可以避免缓存浪费。

In [262]:
x = np.array([1,2,3])
y = np.zeros(6)
y

array([0., 0., 0., 0., 0., 0.])

In [263]:
np.power(2, x, out = y[::2])
y

array([2., 0., 4., 0., 8., 0.])

## 十. 聚合函数

聚合函数，如：求和、乘积、中位数、最大值、最小值、均值、方差……

最常用的三种：
* np.sum
* np.min
* np.max

关于多维度聚合：默认无其他参数的情况下，聚合函数将返回对整个数组聚合的结果。

可以用`axis`参数指定沿哪个轴的方向聚合——对于2维，`axis=0`沿列方向，`axis=1`沿行方向；`axis`指定的是数组将会被折叠的维度。

大多数聚合函数都应版本的NaN-safe函数，即计算时忽略所有的缺失值，只需在名字前面加nan。例如，`np.sum`的缺失值安全版本是`np.nansum`。

其他常用聚合函数：
* np.prod：计算元素的积
* np.mean：平均值
* np.std：标准差
* np.var：方差
* np.argmin：最小值的索引
* np.argmax：最大值的索引
* np.median：中位数
* np.percentile：计算基于元素排序的统计值
* np.any：验证是否存在元素为真
* np.all：验证所有元素是否为真

## 十一. 广播

广播的实质：用于不同大小数组的二元通用函数的一组规则。

[广播的直观理解](https://www.cnblogs.com/yangmang/p/7125458.html)

广播的规则：
* 如果两个数组的维度数量不相同，那么小维度数组的形状将会在最左边补1；
* 维度数量相同后，数组的形状会沿着维度为1的扩展以匹配另外一个数组的形状；
* 如果维度数量相同，但都不匹配且没有为1的，异常。

用途：数据归一化。

In [264]:
np.random.seed(0)
X = np.random.randint(0,100,(3,5))
X

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58]])

In [265]:
X_mean = X.mean(0)
X_mean

array([41.        , 72.66666667, 57.66666667, 38.33333333, 70.66666667])

In [266]:
X_centered = X-X_mean
X_centered

array([[  3.        , -25.66666667,   6.33333333,  28.66666667,
         -3.66666667],
       [-32.        ,  10.33333333, -36.66666667,  -2.33333333,
         16.33333333],
       [ 29.        ,  15.33333333,  30.33333333, -26.33333333,
        -12.66666667]])

## 十二. 比较

场景：希望基于某些准则来抽取、修改、计数或对一个数组中的值进行其他操作。

比较运算符与对应的通用函数(返回布尔数据类型的数组)：
* `==`, np.equal
* `!=`, np.not_equal
* `<`, np.less
* `<=`, np.less_equal
* `>`, np.greater
* `>=`, np.greater_equal

In [267]:
x = np.array([1,2,3,4,5])
x == 3

array([False, False,  True, False, False])

对布尔数组的常用操作：
* `np.count_nonzero()`：统计True的个数
* `np.sum()`：统计True的个数，能够按轴统计
* `np.any()`：是否有True
* `np.all()`：是否全是True

In [268]:
np.count_nonzero(x==3)

1

In [269]:
np.any(x==3)

True

In [270]:
np.all(x==3)

False

使用布尔数组作为掩码，通过该掩码选择数据的子数据集：

In [271]:
x

array([1, 2, 3, 4, 5])

In [272]:
# 抽取x中大于3的元素
x[x>3]

array([4, 5])

In [273]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [274]:
# 抽取y中大于等于7的元素，展开
y[y>=7]

array([ 7,  8,  9, 10, 11])

逐位布尔运算符：
* `&`, np.bitwise_and
* `|`, np.bitwise_or
* `^`, np.bitwise_xor
* `-`, np.bitwise_not

`and`和`or`对整个对象执行单个布尔操作，而`&`和`|`对一个对象的内容执行多个布尔运算，下例：

In [275]:
a = np.array([True, False, True])
b = np.array([True, True, False])

In [276]:
# 对a和b中每一对对应的元素进行“逻辑与”的运算
a & b

array([ True, False, False])

In [277]:
# 对a和b中每一对对应的元素进行“逻辑与或”的运算
a | b

array([ True,  True,  True])

## 十三. 花式索引

fancy indexing，传递一个索引数组来一次性获得多个数组元素。

In [278]:
x = np.array([1,2,3,4,5,6,7])
ind = [0,1,2,3]
x[ind]

array([1, 2, 3, 4])

注意，花哨索引结果的形状与索引数组的形状一致，而不是与被索引数组的形状一致。

In [279]:
ind = np.array([[0,1],[2,3]])
x[ind]

array([[1, 2],
       [3, 4]])

多维数组的花式索引：

In [280]:
X = np.arange(24).reshape((4,6))
X

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [281]:
# 第一个值是X[1,2]，第二个值是X[3,4]
row = np.array([1,3])
col = np.array([2,4])
X[row, col]

array([ 8, 22])

In [282]:
# 广播，十分有用，交叉点元素
X[row[:, np.newaxis], col]

array([[ 8, 10],
       [20, 22]])

## 十四. 排序

一维数组排序：

In [283]:
np.random.seed(0)
a = np.random.randint(0,20,(10))
a

array([12, 15,  0,  3,  3,  7,  9, 19, 18,  4])

In [284]:
# 默认升序
np.sort(a)

array([ 0,  3,  3,  4,  7,  9, 12, 15, 18, 19])

In [285]:
# 数组排好序的索引值
np.argsort(a)

array([2, 3, 4, 9, 5, 6, 0, 1, 8, 7])

In [286]:
# 花式索引
a[np.argsort(a)]

array([ 0,  3,  3,  4,  7,  9, 12, 15, 18, 19])

多维数组排序，用`axis=`指定排序的轴，注意这样排序会导致任何行或列之间的关系丢失！

In [287]:
np.random.seed(1)
X = np.random.randint(0,100,(4,5))
X

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28]])

In [288]:
np.sort(X, axis=0)

array([[ 5, 12,  6,  9,  1],
       [20, 18, 64, 11, 28],
       [37, 71, 72, 16, 50],
       [76, 79, 84, 25, 75]])

In [289]:
np.sort(X, axis=1)

array([[ 9, 12, 37, 72, 75],
       [ 1,  5, 16, 64, 79],
       [ 6, 25, 50, 71, 76],
       [11, 18, 20, 28, 84]])

部分排序：`np.partition(X, K)`，最左边的是K个值，前K个小的值，右边是其他值；两个部分都是各自任意排列的。

In [290]:
b = np.array([19,16,10,2,7,19,4,0,13])
np.partition(b, 4)

array([ 2,  0,  4,  7, 10, 13, 19, 16, 19])